import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'doc',
      id: 'intro', // document ID
      label: 'Get Started', // sidebar label
    },
    {
      type: 'category',
      label: 'Module 1: Foundations & ROS 2',
      items: [{ type: 'autogenerated', dirName: 'module-01-foundations' }],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [{ type: 'autogenerated', dirName: 'module-02-gazebo-unity' }],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [{ type: 'autogenerated', dirName: 'module-03-nvidia-isaac' }],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [{ type: 'autogenerated', dirName: 'module-04-vla' }],
    },
    {
      type: 'doc',
      id: 'conclusion', // document ID
      label: 'Conclusion', // sidebar label
    },
  ],
};

export default sidebars;
