import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'category',
      label: 'Module 1: Foundations & ROS 2',
      items: [{type: 'autogenerated', dirName: 'module-01-foundations'}],
    },
    {
      type: 'category',
      label: 'Module 2: Isaac Sim',
      items: [{type: 'autogenerated', dirName: 'module-02-isaac-sim'}],
    },
    {
      type: 'category',
      label: 'Module 3: Gazebo',
      items: [{type: 'autogenerated', dirName: 'module-03-gazebo'}],
    },
    {
      type: 'category',
      label: 'Module 4: Webots',
      items: [{type: 'autogenerated', dirName: 'module-04-webots'}],
    },
  ],
};

export default sidebars;
